# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
# user = User.create(provider: "abc", uid: "abc", name: "abc", email: "a@a", password: "123", password_confirmation: "123", activated: true)

Country.create(name: "Brunei Darussalam")
Country.create(name: "Cambodia")
Country.create(name: "East Timor")
Country.create(name: "Indonesia")
Country.create(name: "Laos")
Country.create(name: "Malaysia")


Country.create(name: "Myanmar")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")
Country.find_by(name: "Myanmar").cities.create(name: "")


Country.create(name: "Philippines")
Country.find_by(name: "Philippines").cities.create(name: "Alaminos")
Country.find_by(name: "Philippines").cities.create(name: "Angeles")
Country.find_by(name: "Philippines").cities.create(name: "Antipolo")
Country.find_by(name: "Philippines").cities.create(name: "Bacolod")
Country.find_by(name: "Philippines").cities.create(name: "Bacoor")
Country.find_by(name: "Philippines").cities.create(name: "Bago")
Country.find_by(name: "Philippines").cities.create(name: "Baguio")
Country.find_by(name: "Philippines").cities.create(name: "Bais")
Country.find_by(name: "Philippines").cities.create(name: "Balanga")
Country.find_by(name: "Philippines").cities.create(name: "Batac")
Country.find_by(name: "Philippines").cities.create(name: "Batangas")
Country.find_by(name: "Philippines").cities.create(name: "Bayawan")
Country.find_by(name: "Philippines").cities.create(name: "Baybay")
Country.find_by(name: "Philippines").cities.create(name: "Bayugan ")
Country.find_by(name: "Philippines").cities.create(name: "Biñan")
Country.find_by(name: "Philippines").cities.create(name: "Bislig")
Country.find_by(name: "Philippines").cities.create(name: "Bogo")
Country.find_by(name: "Philippines").cities.create(name: "Borongan")
Country.find_by(name: "Philippines").cities.create(name: "Butuan")
Country.find_by(name: "Philippines").cities.create(name: "Cabadbaran")
Country.find_by(name: "Philippines").cities.create(name: "Cabanatuan")
Country.find_by(name: "Philippines").cities.create(name: "Cabuyao")
Country.find_by(name: "Philippines").cities.create(name: "Cadiz")
Country.find_by(name: "Philippines").cities.create(name: "Cagayan de Oro")
Country.find_by(name: "Philippines").cities.create(name: "Calamba")
Country.find_by(name: "Philippines").cities.create(name: "Calapan")
Country.find_by(name: "Philippines").cities.create(name: "Calbayogv")
Country.find_by(name: "Philippines").cities.create(name: "Caloocan")
Country.find_by(name: "Philippines").cities.create(name: "Candon")
Country.find_by(name: "Philippines").cities.create(name: "Canlaon")
Country.find_by(name: "Philippines").cities.create(name: "Carcar")
Country.find_by(name: "Philippines").cities.create(name: "Catbalogan")
Country.find_by(name: "Philippines").cities.create(name: "Cauayan")
Country.find_by(name: "Philippines").cities.create(name: "Cavite City")
Country.find_by(name: "Philippines").cities.create(name: "Cebu City")
Country.find_by(name: "Philippines").cities.create(name: "Cotabato City")
Country.find_by(name: "Philippines").cities.create(name: "Dagupan")
Country.find_by(name: "Philippines").cities.create(name: "Danao")
Country.find_by(name: "Philippines").cities.create(name: "Dapitan")
Country.find_by(name: "Philippines").cities.create(name: "Dasmariñas")
Country.find_by(name: "Philippines").cities.create(name: "Davao City")
Country.find_by(name: "Philippines").cities.create(name: "Digos")
Country.find_by(name: "Philippines").cities.create(name: "Dipolog")
Country.find_by(name: "Philippines").cities.create(name: "Dumaguete")
Country.find_by(name: "Philippines").cities.create(name: "El Salvador")
Country.find_by(name: "Philippines").cities.create(name: "Escalante")
Country.find_by(name: "Philippines").cities.create(name: "Gapan")
Country.find_by(name: "Philippines").cities.create(name: "General Santos")
Country.find_by(name: "Philippines").cities.create(name: "General Trias")
Country.find_by(name: "Philippines").cities.create(name: "Gingoog")
Country.find_by(name: "Philippines").cities.create(name: "Guihulngan")
Country.find_by(name: "Philippines").cities.create(name: "Himamaylan")
Country.find_by(name: "Philippines").cities.create(name: "Ilagan")
Country.find_by(name: "Philippines").cities.create(name: "Iligan")
Country.find_by(name: "Philippines").cities.create(name: "Iloilo City")
Country.find_by(name: "Philippines").cities.create(name: "Imus")
Country.find_by(name: "Philippines").cities.create(name: "Iriga")
Country.find_by(name: "Philippines").cities.create(name: "Isabela")
Country.find_by(name: "Philippines").cities.create(name: "Kabankalan")
Country.find_by(name: "Philippines").cities.create(name: "Kidapawan")
Country.find_by(name: "Philippines").cities.create(name: "Koronadal")
Country.find_by(name: "Philippines").cities.create(name: "La Carlota")
Country.find_by(name: "Philippines").cities.create(name: "Lamitan")
Country.find_by(name: "Philippines").cities.create(name: "Laoag")
Country.find_by(name: "Philippines").cities.create(name: "Lapu‑Lapu")
Country.find_by(name: "Philippines").cities.create(name: "Las Piñas")
Country.find_by(name: "Philippines").cities.create(name: "Legazpi")
Country.find_by(name: "Philippines").cities.create(name: "Ligao")
Country.find_by(name: "Philippines").cities.create(name: "Lipa")
Country.find_by(name: "Philippines").cities.create(name: "Lucena")
Country.find_by(name: "Philippines").cities.create(name: "Maasin")
Country.find_by(name: "Philippines").cities.create(name: "Mabalacat")
Country.find_by(name: "Philippines").cities.create(name: "Makati")
Country.find_by(name: "Philippines").cities.create(name: "Malabon")
Country.find_by(name: "Philippines").cities.create(name: "Malaybalay")
Country.find_by(name: "Philippines").cities.create(name: "Malolos")
Country.find_by(name: "Philippines").cities.create(name: "Mandaluyong")
Country.find_by(name: "Philippines").cities.create(name: "Mandaue")
Country.find_by(name: "Philippines").cities.create(name: "Manila")
Country.find_by(name: "Philippines").cities.create(name: "Marawi")
Country.find_by(name: "Philippines").cities.create(name: "Marikina")
Country.find_by(name: "Philippines").cities.create(name: "Masbate City")
Country.find_by(name: "Philippines").cities.create(name: "Mati")
Country.find_by(name: "Philippines").cities.create(name: "Meycauayan")
Country.find_by(name: "Philippines").cities.create(name: "Muñoz")
Country.find_by(name: "Philippines").cities.create(name: "Muntinlupa")
Country.find_by(name: "Philippines").cities.create(name: "Naga")
Country.find_by(name: "Philippines").cities.create(name: "Navotas")
Country.find_by(name: "Philippines").cities.create(name: "Olongapo")
Country.find_by(name: "Philippines").cities.create(name: "Ormoc")
Country.find_by(name: "Philippines").cities.create(name: "Oroquieta")
Country.find_by(name: "Philippines").cities.create(name: "Ozamiz")
Country.find_by(name: "Philippines").cities.create(name: "Pagadian")
Country.find_by(name: "Philippines").cities.create(name: "Pagadian")
Country.find_by(name: "Philippines").cities.create(name: "Panabo")
Country.find_by(name: "Philippines").cities.create(name: "Parañaque")
Country.find_by(name: "Philippines").cities.create(name: "Pasay")
Country.find_by(name: "Philippines").cities.create(name: "Pasig")
Country.find_by(name: "Philippines").cities.create(name: "Passi")
Country.find_by(name: "Philippines").cities.create(name: "Puerto Princesa")
Country.find_by(name: "Philippines").cities.create(name: "Quezon City")
Country.find_by(name: "Philippines").cities.create(name: "Roxas")
Country.find_by(name: "Philippines").cities.create(name: "Sagay")
Country.find_by(name: "Philippines").cities.create(name: "Samal")
Country.find_by(name: "Philippines").cities.create(name: "San Carlos")
Country.find_by(name: "Philippines").cities.create(name: "San Fernando")
Country.find_by(name: "Philippines").cities.create(name: "San Jose")
Country.find_by(name: "Philippines").cities.create(name: "San Jose del Monte")
Country.find_by(name: "Philippines").cities.create(name: "San Juan")
Country.find_by(name: "Philippines").cities.create(name: "San Pablo")
Country.find_by(name: "Philippines").cities.create(name: "San Pedro")
Country.find_by(name: "Philippines").cities.create(name: "Santa Rosa")
Country.find_by(name: "Philippines").cities.create(name: "Santiago")
Country.find_by(name: "Philippines").cities.create(name: "Silay")
Country.find_by(name: "Philippines").cities.create(name: "Sipalay")
Country.find_by(name: "Philippines").cities.create(name: "Sorsogon City")
Country.find_by(name: "Philippines").cities.create(name: "Surigao City")
Country.find_by(name: "Philippines").cities.create(name: "Tabaco")
Country.find_by(name: "Philippines").cities.create(name: "Tabuk")
Country.find_by(name: "Philippines").cities.create(name: "Tacloban")
Country.find_by(name: "Philippines").cities.create(name: "Tacurong")
Country.find_by(name: "Philippines").cities.create(name: "Tagaytay")
Country.find_by(name: "Philippines").cities.create(name: "Tagbilaran")
Country.find_by(name: "Philippines").cities.create(name: "Taguig")
Country.find_by(name: "Philippines").cities.create(name: "Tagum")
Country.find_by(name: "Philippines").cities.create(name: "Talisay")
Country.find_by(name: "Philippines").cities.create(name: "Talisay")
Country.find_by(name: "Philippines").cities.create(name: "Tanauan")
Country.find_by(name: "Philippines").cities.create(name: "Tandag")
Country.find_by(name: "Philippines").cities.create(name: "Tangub")
Country.find_by(name: "Philippines").cities.create(name: "Tanjay")
Country.find_by(name: "Philippines").cities.create(name: "Tarlac City")
Country.find_by(name: "Philippines").cities.create(name: "Tayabas")
Country.find_by(name: "Philippines").cities.create(name: "Toledo")
Country.find_by(name: "Philippines").cities.create(name: "Trece Martires")
Country.find_by(name: "Philippines").cities.create(name: "Tuguegarao")
Country.find_by(name: "Philippines").cities.create(name: "Urdaneta")
Country.find_by(name: "Philippines").cities.create(name: "Valencia")
Country.find_by(name: "Philippines").cities.create(name: "Valenzuela")
Country.find_by(name: "Philippines").cities.create(name: "Victorias")
Country.find_by(name: "Philippines").cities.create(name: "Vigan")
Country.find_by(name: "Philippines").cities.create(name: "Zamboanga City")
Country.find_by(name: "Philippines").cities.create(name: "")


Country.create(name: "Singapore")
Country.find_by(name: "Singapore").cities.create(name: "Singapore")


Country.create(name: "Thailand")
Country.find_by(name: "Thailand").cities.create(name: "Bangkok")
Country.find_by(name: "Thailand").cities.create(name: "Nonthaburi")
Country.find_by(name: "Thailand").cities.create(name: "Nakhon Ratchasima")
Country.find_by(name: "Thailand").cities.create(name: "Chiang Mai")
Country.find_by(name: "Thailand").cities.create(name: "Hat Yai")
Country.find_by(name: "Thailand").cities.create(name: "Udon Thani")
Country.find_by(name: "Thailand").cities.create(name: "Pak Kret")
Country.find_by(name: "Thailand").cities.create(name: "Chaophraya Surasak")
Country.find_by(name: "Thailand").cities.create(name: "Khon Kaen")
Country.find_by(name: "Thailand").cities.create(name: "Ubon Ratchathani")
Country.find_by(name: "Thailand").cities.create(name: "Nakhon Si Thammarat")
Country.find_by(name: "Thailand").cities.create(name: "Nakhon Sawan")
Country.find_by(name: "Thailand").cities.create(name: "Nakhon Pathom")
Country.find_by(name: "Thailand").cities.create(name: "Phitsanulok")
Country.find_by(name: "Thailand").cities.create(name: "Pattaya")
Country.find_by(name: "Thailand").cities.create(name: "Songkhla")
Country.find_by(name: "Thailand").cities.create(name: "Surat Thani")
Country.find_by(name: "Thailand").cities.create(name: "Rangsit")
Country.find_by(name: "Thailand").cities.create(name: "Yala")
Country.find_by(name: "Thailand").cities.create(name: "Phuket")
Country.find_by(name: "Thailand").cities.create(name: "Samut Prakan")
Country.find_by(name: "Thailand").cities.create(name: "Lampang")
Country.find_by(name: "Thailand").cities.create(name: "Laem Chabang")
Country.find_by(name: "Thailand").cities.create(name: "Chiang Rai")
Country.find_by(name: "Thailand").cities.create(name: "Trang")
Country.find_by(name: "Thailand").cities.create(name: "Phra Nakhon Si Ayutthaya")
Country.find_by(name: "Thailand").cities.create(name: "Ko Samui")
Country.find_by(name: "Thailand").cities.create(name: "Samut Sakhon")
Country.find_by(name: "Thailand").cities.create(name: "Rayong")
Country.find_by(name: "Thailand").cities.create(name: "Mae Sot")
Country.find_by(name: "Thailand").cities.create(name: "Om Noi")
Country.find_by(name: "Thailand").cities.create(name: "Sakon Nakhon")



Country.create(name: "Vietnam")
Country.find_by(name: "Vietnam").cities.create(name: "Cần Thơ")
Country.find_by(name: "Vietnam").cities.create(name: "Đà Nẵng")
Country.find_by(name: "Vietnam").cities.create(name: "Hải Phòng")
Country.find_by(name: "Vietnam").cities.create(name: "Hà Nội")
Country.find_by(name: "Vietnam").cities.create(name: "Hồ Chí Minh City")
Country.find_by(name: "Vietnam").cities.create(name: "Bà Rịa")
Country.find_by(name: "Vietnam").cities.create(name: "Bạc Liêu")
Country.find_by(name: "Vietnam").cities.create(name: "Bảo Lộc")
Country.find_by(name: "Vietnam").cities.create(name: "Bắc Giang")
Country.find_by(name: "Vietnam").cities.create(name: "Bắc Kạn")
Country.find_by(name: "Vietnam").cities.create(name: "Bắc Ninh")
Country.find_by(name: "Vietnam").cities.create(name: "Bến Tre")
Country.find_by(name: "Vietnam").cities.create(name: "Biên Hòa")
Country.find_by(name: "Vietnam").cities.create(name: "Buôn Ma Thuột")
Country.find_by(name: "Vietnam").cities.create(name: "Cà Mau")
Country.find_by(name: "Vietnam").cities.create(name: "Cam Ranh")
Country.find_by(name: "Vietnam").cities.create(name: "Cao Bằng")
Country.find_by(name: "Vietnam").cities.create(name: "Cao Lãnh")
Country.find_by(name: "Vietnam").cities.create(name: "Cẩm Phả")
Country.find_by(name: "Vietnam").cities.create(name: "Châu Đốc")
Country.find_by(name: "Vietnam").cities.create(name: "Đà Lạt")
Country.find_by(name: "Vietnam").cities.create(name: "Điện Biên Phủ")
Country.find_by(name: "Vietnam").cities.create(name: "Đông Hà")
Country.find_by(name: "Vietnam").cities.create(name: "Đồng Hới")
Country.find_by(name: "Vietnam").cities.create(name: "Hà Giang")
Country.find_by(name: "Vietnam").cities.create(name: "Hạ Long")
Country.find_by(name: "Vietnam").cities.create(name: "Hà Tĩnh")
Country.find_by(name: "Vietnam").cities.create(name: "Hải Dương")
Country.find_by(name: "Vietnam").cities.create(name: "Hòa Bình")
Country.find_by(name: "Vietnam").cities.create(name: "Hội An")
Country.find_by(name: "Vietnam").cities.create(name: "Huế")
Country.find_by(name: "Vietnam").cities.create(name: "Hưng Yên")
Country.find_by(name: "Vietnam").cities.create(name: "Kon Tum")
Country.find_by(name: "Vietnam").cities.create(name: "Lai Châu")
Country.find_by(name: "Vietnam").cities.create(name: "Lạng Sơn")
Country.find_by(name: "Vietnam").cities.create(name: "Lào Cai")
Country.find_by(name: "Vietnam").cities.create(name: "Long Xuyên")
Country.find_by(name: "Vietnam").cities.create(name: "Móng Cái")
Country.find_by(name: "Vietnam").cities.create(name: "Mỹ Tho")
Country.find_by(name: "Vietnam").cities.create(name: "Nam Định")
Country.find_by(name: "Vietnam").cities.create(name: "Nha Trang")
Country.find_by(name: "Vietnam").cities.create(name: "Ninh Bình")
Country.find_by(name: "Vietnam").cities.create(name: "Phan Rang–Tháp Chàm")
Country.find_by(name: "Vietnam").cities.create(name: "Phan Thiết")
Country.find_by(name: "Vietnam").cities.create(name: "Phủ Lý")
Country.find_by(name: "Vietnam").cities.create(name: "Pleikuv")
Country.find_by(name: "Vietnam").cities.create(name: "Quảng Ngãi")
Country.find_by(name: "Vietnam").cities.create(name: "Quy Nhơn")
Country.find_by(name: "Vietnam").cities.create(name: "Rạch Giá")
Country.find_by(name: "Vietnam").cities.create(name: "Sa Đéc")
Country.find_by(name: "Vietnam").cities.create(name: "Sầm Sơn")
Country.find_by(name: "Vietnam").cities.create(name: "Sóc Trăng")
Country.find_by(name: "Vietnam").cities.create(name: "Sông Công")
Country.find_by(name: "Vietnam").cities.create(name: "Sơn La")
Country.find_by(name: "Vietnam").cities.create(name: "Tam Điệp")
Country.find_by(name: "Vietnam").cities.create(name: "Tam Kỳ")
Country.find_by(name: "Vietnam").cities.create(name: "Tân An")
Country.find_by(name: "Vietnam").cities.create(name: "Tây Ninh")
Country.find_by(name: "Vietnam").cities.create(name: "Thái Bình")
Country.find_by(name: "Vietnam").cities.create(name: "Thái Nguyên")
Country.find_by(name: "Vietnam").cities.create(name: "Thanh Hóa")
Country.find_by(name: "Vietnam").cities.create(name: "Thủ Dầu Một")
Country.find_by(name: "Vietnam").cities.create(name: "Trà Vinh")
Country.find_by(name: "Vietnam").cities.create(name: "Tuy Hòa")
Country.find_by(name: "Vietnam").cities.create(name: "Tuyên Quang")
Country.find_by(name: "Vietnam").cities.create(name: "Uông Bív")
Country.find_by(name: "Vietnam").cities.create(name: "Vị Thanh")
Country.find_by(name: "Vietnam").cities.create(name: "Việt Trì")
Country.find_by(name: "Vietnam").cities.create(name: "Vinh")
Country.find_by(name: "Vietnam").cities.create(name: "Vĩnh Long")
Country.find_by(name: "Vietnam").cities.create(name: "Vĩnh Yên")
Country.find_by(name: "Vietnam").cities.create(name: "Vũng Tàu")
Country.find_by(name: "Vietnam").cities.create(name: "Yên Bái")



# Country.create(name: "Afghanistan")
# Country.create(name: "Albania")
# Country.create(name: "Algeria")
# Country.create(name: "Andorra")
# Country.create(name: "Angola")
# Country.create(name: "Antigua and Barbuda")
# Country.create(name: "Argentina")
# Country.create(name: "Armenia")
# Country.create(name: "Aruba")
# Country.create(name: "Australia")
# Country.create(name: "Austria")
# Country.create(name: "Azerbaijan")
#
# Country.create(name: "Bahamas, The")
# Country.create(name: "Bahrain")
# Country.create(name: "Bangladesh")
# Country.create(name: "Barbados")
# Country.create(name: "Belarus")
# Country.create(name: "Belgium")
# Country.create(name: "Belize")
# Country.create(name: "Benin")
# Country.create(name: "Bhutan")
# Country.create(name: "Bolivia")
# Country.create(name: "Bosnia and Herzegovina")
# Country.create(name: "Botswana")
# Country.create(name: "Brazil")
# Country.create(name: "Brunei")
# Country.create(name: "Bulgaria")
# Country.create(name: "Burkina Faso")
# Country.create(name: "Burma")
# Country.create(name: "Burundi")
#
# Country.create(name: "Cambodia")
# Country.create(name: "Cameroon")
# Country.create(name: "Canada")
# Country.create(name: "Cabo Verde")
# Country.create(name: "Central African Republic")
# Country.create(name: "Chad")
# Country.create(name: "Chile")
# Country.create(name: "China")
# Country.create(name: "Colombia")
# Country.create(name: "Comoros")
# Country.create(name: "Congo, Democratic Republic of the")
# Country.create(name: "Congo, Republic of the")
# Country.create(name: "Costa Rica")
# Country.create(name: "Cote d'Ivoire")
# Country.create(name: "Croatia")
# Country.create(name: "Cuba")
# Country.create(name: "Curacao")
# Country.create(name: "Cyprus")
# Country.create(name: "Czechia")
#
# Country.create(name: "Denmark")
# Country.create(name: "Djibouti")
# Country.create(name: "Dominica")
# Country.create(name: "Dominican Republic")
#
# Country.create(name: "East Timor (see Timor-Leste)")
# Country.create(name: "Ecuador")
# Country.create(name: "Egypt")
# Country.create(name: "El Salvador")
# Country.create(name: "Equatorial Guinea")
# Country.create(name: "Eritrea")
# Country.create(name: "Estonia")
# Country.create(name: "Ethiopia")
#
# Country.create(name: "Fiji")
# Country.create(name: "Finland")
# Country.create(name: "France")
#
# Country.create(name: "Gabon")
# Country.create(name: "Gambia, The")
# Country.create(name: "Georgia")
# Country.create(name: "Germany")
# Country.create(name: "Ghana")
# Country.create(name: "Greece")
# Country.create(name: "Grenada")
# Country.create(name: "Guatemala")
# Country.create(name: "Guinea")
# Country.create(name: "Guinea-Bissau")
# Country.create(name: "Guyana")
#
# Country.create(name: "Haiti")
# Country.create(name: "Holy See")
# Country.create(name: "Honduras")
# Country.create(name: "Hong Kong")
# Country.create(name: "Hungary")
#
# Country.create(name: "Iceland")
# Country.create(name: "India")
# Country.create(name: "Indonesia")
# Country.create(name: "Iran")
# Country.create(name: "Iraq")
# Country.create(name: "Ireland")
# Country.create(name: "Israel")
# Country.create(name: "Italy")
#
# Country.create(name: "Jamaica")
# Country.create(name: "Japan")
# Country.create(name: "Jordan")
#
# Country.create(name: "Kazakhstan")
# Country.create(name: "Kenya")
# Country.create(name: "Kiribati")
# Country.create(name: "Korea, North")
# Country.create(name: "Korea, South")
# Country.create(name: "Kosovo")
# Country.create(name: "Kuwait")
# Country.create(name: "Kyrgyzstan")
#
# Country.create(name: "Laos")
# Country.create(name: "Latvia")
# Country.create(name: "Lebanon")
# Country.create(name: "Lesotho")
# Country.create(name: "Liberia")
# Country.create(name: "Libya")
# Country.create(name: "Liechtenstein")
# Country.create(name: "Lithuania")
# Country.create(name: "Luxembourg")
#
# Country.create(name: "Macau")
# Country.create(name: "Macedonia")
# Country.create(name: "Madagascar")
# Country.create(name: "Malawi")
# Country.create(name: "Malaysia")
# Country.create(name: "Maldives")
# Country.create(name: "Mali")
# Country.create(name: "Malta")
# Country.create(name: "Marshall Islands")
# Country.create(name: "Mauritania")
# Country.create(name: "Mauritius")
# Country.create(name: "Mexico")
# Country.create(name: "Micronesia")
# Country.create(name: "Moldova")
# Country.create(name: "Monaco")
# Country.create(name: "Mongolia")
# Country.create(name: "Montenegro")
# Country.create(name: "Morocco")
# Country.create(name: "Mozambique")
#
# Country.create(name: "Namibia")
# Country.create(name: "Nauru")
# Country.create(name: "Nepal")
# Country.create(name: "Netherlands")
# Country.create(name: "New Zealand")
# Country.create(name: "Nicaragua")
# Country.create(name: "Niger")
# Country.create(name: "Nigeria")
# Country.create(name: "North Korea")
# Country.create(name: "Norway")
#
# Country.create(name: "Oman")
#
# Country.create(name: "Pakistan")
# Country.create(name: "Palau")
# Country.create(name: "Palestinian Territories")
# Country.create(name: "Panama")
# Country.create(name: "Papua New Guinea")
# Country.create(name: "Paraguay")
# Country.create(name: "Peru")
# Country.create(name: "Philippines")
# Country.create(name: "Poland")
# Country.create(name: "Portugal")
#
# Country.create(name: "Qatar")
#
# Country.create(name: "Romania")
# Country.create(name: "Russia")
# Country.create(name: "Rwanda")
#
# Country.create(name: "Saint Kitts and Nevis")
# Country.create(name: "Saint Lucia")
# Country.create(name: "Saint Vincent and the Grenadines")
# Country.create(name: "Samoa")
# Country.create(name: "San Marino")
# Country.create(name: "Sao Tome and Principe")
# Country.create(name: "Saudi Arabia")
# Country.create(name: "Senegal")
# Country.create(name: "Serbia")
# Country.create(name: "Seychelles")
# Country.create(name: "Sierra Leone")
# Country.create(name: "Singapore")
# Country.create(name: "Sint Maarten")
# Country.create(name: "Slovakia")
# Country.create(name: "Slovenia")
# Country.create(name: "Solomon Islands")
# Country.create(name: "Somalia")
# Country.create(name: "South Africa")
# Country.create(name: "South Korea")
# Country.create(name: "South Sudan")
# Country.create(name: "Spain")
# Country.create(name: "Sri Lanka")
# Country.create(name: "Sudan")
# Country.create(name: "Suriname")
# Country.create(name: "Swaziland")
# Country.create(name: "Sweden")
# Country.create(name: "Switzerland")
# Country.create(name: "Syria")
#
# Country.create(name: "Taiwan")
# Country.create(name: "Tajikistan")
# Country.create(name: "Tanzania")
# Country.create(name: "Thailand")
# Country.create(name: "Timor-Leste")
# Country.create(name: "Togo")
# Country.create(name: "Tonga")
# Country.create(name: "Trinidad and Tobago")
# Country.create(name: "Tunisia")
# Country.create(name: "Turkey")
# Country.create(name: "Turkmenistan")
# Country.create(name: "Tuvalu")
#
# Country.create(name: "Uganda")
# Country.create(name: "Ukraine")
# Country.create(name: "United Arab Emirates")
# Country.create(name: "United Kingdom")
# Country.create(name: "Uruguay")
# Country.create(name: "Uzbekistan")
#
# Country.create(name: "Vanuatu")
# Country.create(name: "Venezuela")
# Country.create(name: "Vietnam")
#
# Country.create(name: "Yemen")
#
# Country.create(name: "Zambia")
# Country.create(name: "Zimbabwe")
